name: Node 24 Test Workflow
on: [push]

jobs:
  test-node:
    runs-on: self-hosted  # O'zingizni runneringiz bo'lgani uchun
    steps:
      - name: Repo-ni yuklash
        uses: actions/checkout@v4

      - name: Node.js 24-ni o'rnatish
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Versiyani va Env-ni tekshirish
        run: |
          node -v
          echo "Hozirgi muhit: $APP_STATUS"
        env:
          APP_STATUS: "Node 24 migration test" # Rasmda aytilgan env set qilish
